src/controllers/DefaultController.php
<?php

namespace zhuzixian520\api_doc\controllers;

use Yii;
use yii\helpers\FileHelper;
use yii\helpers\Inflector;
use yii\helpers\StringHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use zhuzixian520\api_doc\AnnotationHelper;

class DefaultController extends Controller
{
    /**
     * @var \zhuzixian520\api_doc\Module
     */
    public $module;

    public function init()
    {
        parent::init();

        //给当前view设置params参数，给layout传参
        Yii::$app->view->params = $this->_getLoyoutParams();
    }

    /**
     * {@inheritdoc}
     */
    public function beforeAction($action)
    {
        Yii::$app->response->format = Response::FORMAT_HTML;
        return parent::beforeAction($action);
    }

    public function actionIndex()
    {
        $this->layout = 'main';

        $version = (int)Yii::$app->request->get('v', 1);
        if ($version == 0){
            $version = 'v1';
        }else {
            $version = 'v' . $version;
        }

        $apiModuleList = $this->_getApiModuleList($version);

        $data = [
            'apiModuleList' => $apiModuleList,
            'ver' => $version,
        ];

        return $this->render('index', $data);
    }

    public function actionView()
    {
        $this->layout = 'main';

        $route = Yii::$app->request->get('route');
        $ver = Yii::$app->request->get('ver');
        $arr = explode('/',$route);
        //if (count($arr) != 4 || in_array('',$arr)){
        if (count($arr) != 3 || in_array('',$arr)){
            throw new NotFoundHttpException('您输入的地址页面不存在');
        }

        //$c_name = Inflector::id2camel(StringHelper::mb_ucfirst($arr[2])).'Controller';
        $c_name = Inflector::id2camel(StringHelper::mb_ucfirst($arr[1])).'Controller';
        //$class = 'api\modules\\'.$arr[0].'\\controllers\\'.$arr[1]. '\\' .$c_name;
        //$class = 'api_cms\modules\\' . $arr[0]. '\\controllers\\' . $c_name;
        $class = Yii::$app->getModule($arr[0])->controllerNamespace . '\\' . $c_name;

        //$res = strpos($arr[3], '-');
        $res = strpos($arr[2], '-');
        if ($res){
            //$a = FormatHelper::trimAll(StringHelper::mb_ucwords(str_replace('-', ' ', $arr[3])));
            $a = AnnotationHelper::trimAll(StringHelper::mb_ucwords(str_replace('-', ' ', $arr[2])));
        }else{
            //$a = StringHelper::mb_ucfirst($arr[3]);
            $a = StringHelper::mb_ucfirst($arr[2]);
        }
        $method = 'action'.$a;

        try {
            $notes = AnnotationHelper::getNoteDetail($class, $method);
        } catch (\ReflectionException $e){
            //return $e->getMessage();
            throw new NotFoundHttpException($e->getMessage());
        }

        $data = [
            'notes' => $notes,
            'route' => $route,
            'ver' => $ver,
            //'tab_name' => $arr[1],
        ];

        return $this->render('view', $data);
    }

    private function _getLoyoutParams()
    {
        return [
            'host_api' => $this->_getApiHost(),
            'author' => $this->module->author,
            'email' => $this->module->email,

            'logo_src' => $this->module->logo_src,
            'icp_num' => $this->module->icp_num,
            'icp_website' => $this->module->icp_website,
            'copyright_website' => $this->module->copyright_website,
            'company_start_year' => $this->module->company_start_year,
            'is_show_fae' => $this->module->is_show_fae,
            'fae_name' => $this->module->fae_name,
            'fae_website' => $this->module->fae_website,
        ];
    }

    private function _getApiHost()
    {
        $env = YII_ENV;
        switch ($env) {
            case YII_ENV_DEV:
                $host_api = $this->module->hostApiDev;
                break;
            case YII_ENV_PROD:
                $host_api = $this->module->hostApiProd;
                break;
            case YII_ENV_TEST:
                $host_api = $this->module->hostApiTest;
                break;
            default:
                $host_api = '';
        }

        return $host_api;
    }

    private function _getApiModuleList($version)
    {
        //$yii2_modules = Yii::$app->modules;
        //unset($yii2_modules['gii']);
        //unset($yii2_modules['debug']);
        $module = Yii::$app->getModule($version);//获取版本模块
        if (!$module) {
            throw new NotFoundHttpException('您输入的地址页面不存在');
        }

        $controller_path = $module->getControllerPath();//获取控制器主路径

        //$folder_arr = FileHelper::findDirectories($controller_path);//获取控制器主文件夹下的子文件数组
        $folder = $controller_path;
        $apiModuleList = [];
        //foreach ($folder_arr as $k => $folder) {
        $controllers = FileHelper::findFiles($folder, ['recursive' => true]);
        $base_path = dirname(Yii::getAlias('@app'));
        foreach ($controllers as $k2 => $controller) {
            //获取控制器的类名，含命名空间
            $c_name_temp = str_replace([$base_path, '.php', '/'], ['', '', '\\'], $controller);
            $c_name = mb_substr($c_name_temp, 1);

            $contents = file_get_contents($controller);
            $controllerId = Inflector::camel2id(substr(basename($controller), 0, -14));

            preg_match_all('/public function action(\w+?)\(/', $contents, $result);
            foreach ($result[1] as $k3 => $action) {
                $methods = AnnotationHelper::getNoteDetail($c_name, 'action' . $action);
                $actionId = Inflector::camel2id($action);

                /*$ctrl = str_replace($controller_path . DIRECTORY_SEPARATOR, '', $folder_arr[$k]);
                $route = $ctrl . '/' . $controllerId . '/' . $actionId;
                $apiModuleList[$ctrl][$route] = $methods;
                $apiModuleList[$ctrl][$route]['route'] = $route;
                asort($apiModuleList[$ctrl][$route]);*/

                $route = $controllerId . '/' . $actionId;
                $apiModuleList[$route] = $methods;
                $apiModuleList[$route]['route'] = $route;
                asort($apiModuleList[$route]);
            }
        }
        //}
        return $apiModuleList;
    }
}

src/views/default/index.php
<?php

/* @var $this yii\web\View */
/* @var $ver string */
/* @var $apiModuleList array */

use yii\helpers\Url;

$host_api = $this->params['host_api'] ?? '';
$author = $this->params['author'] ?? '';
$email = $this->params['email'] ?? '';

$this->title = 'API文档 ' . $ver . '.0.0'. ' - '. Yii::$app->name;

?>
<div class="index">
    <div class="alert alert-warning" role="alert"><strong>API统一地址：</strong><?= $host_api . '/' . $ver . '/';?> + 接口服务</div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>#</th>
            <th>接口服务</th>
            <th>接口名称</th>
            <th>请求方法</th>
            <th>更多说明</th>
        </tr>
        </thead>
        <tbody>
        <?php $j=0; foreach ($apiModuleList as $k => $v){?>
            <tr>
                <td><?= $j+1;?></td>
                <td><a href="<?= Url::toRoute(['default/view', 'route' => $ver. '/' .$v['route'], 'ver' => $ver, ]);?>" target='_blank'><?= $v['route'];?></a></td>
                <td><?= $v['name'];?></td>
                <td><label class='label <?= $v['method'] == 'POST' ? 'label-primary' : 'label-success';?>'><?= strtoupper($v['method']);?></label></td>
                <td><?= $v['desc'];?></td>
            </tr>
            <?php $j++;}?>
        </tbody>
    </table>
    <div class="alert alert-success" role="alert">
        <strong>温馨提示：</strong> 此接口服务列表根据后台代码自动生成，如有疑问，请咨询PHP架构师 <?= $author;?>，邮箱：<a href="mailto:<?= $email;?>"><?= $email;?></a>
    </div>
</div>

src/views/default/view.php
<?php

/* @var $this yii\web\View */
/* @var $notes array*/
/* @var $route string */
/* @var $ver string */

use yii\helpers\Url;
use yii\web\View;
use yii\widgets\Breadcrumbs;

$host_api = $this->params['host_api'] ?? '';
$author = $this->params['author'] ?? '';
$email = $this->params['email'] ?? '';

//$this->title = 'API文档 ' . $ver . '.0.0'. ' - '. Yii::$app->name;
$this->title = $notes['name'] . ' - ' . Yii::$app->name . ' API文档 ' . $ver . '.0.0';
//$this->params['breadcrumbs'][] = '接口 - ' . $notes['name'];
$token = $notes['token'] ?? 0;
?>
<div>
    <?= Breadcrumbs::widget([
        'homeLink' => [
            'label' => '首页',
            'url' => ['/'],
            'template' => '<li><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp;&nbsp;{link}</li>'
        ],
        'itemTemplate' => "<li>{link}</li>\n", //全局模板  运用到每个link
        'links' => [
            /*[
            'label' => '文章列表',
            'url' => ['site/index'],
            'template' => "<li>{link}</li>" //只会引用到该类模板
            ],
            [
            'label' => '文章详情',
            'url' => ['site/view', 'id'=>1]//如果需要传参这种格式
            ],*/
            '接口 - ' . $notes['name'],//没有链接的
        ],
        'options' => [//设置html属性
            'class' => 'breadcrumb',
        ],
    ]);?>
    <div class="alert alert-warning" role="alert">
        <strong>地址：</strong>
        <span style="margin-left: 5px;color:red;word-break: break-all;"><?= $host_api . '/' . $route;?></span>
    </div>
    <div class="page-header">
        <h4><span class="glyphicon glyphicon-open" aria-hidden="true"></span> 请求参数</h4>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>参数名</th>
            <th>类型</th>
            <th>是否必须</th>
            <th>说明</th>
        </tr>
        </thead>
        <tbody>
        <?php if($token != 0){?>
            <tr>
                <td>token</td>
                <td>string</td>
                <td><label class="label label-primary"><?= $token == 1 ? '是' : '否';?></label></td>
                <td>用户登录认证秘钥【请在Header头Authorization里面传递】</td>
            </tr>
        <?php }?>
        </tbody>
    </table>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>参数名</th>
            <th>类型</th>
            <th>是否必须</th>
            <th>默认值</th>
            <th>说明</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($notes['param'] as $v){?>
            <tr>
                <td><?= $v[1];?></td>
                <td><?= $v[0];?></td>
                <td><label class="label <?= isset($v[3]) && $v[3]=='否'? 'label-default' : 'label-primary';?> label"><?= isset($v[3]) ? $v[3] : '';?></label></td>
                <td><?= isset($v[4]) ? $v[4] : '';?></td>

                <td><?= $v[2];?></td>
            </tr>
        <?php }?>
        </tbody>
    </table>
    <div class="page-header">
        <h4><span class="glyphicon glyphicon-save" aria-hidden="true"></span> 返回参数</h4>
    </div>
    <table class="table table-bordered" >
        <thead>
        <tr><th>返回字段</th><th>类型</th><th>说明</th></tr>
        </thead>
        <tbody>
        <tr>
            <td>name</td>
            <td>string</td>
            <td>HTTP Status Name</td>
        </tr>
        <tr>
            <td>message</td>
            <td>string</td>
            <td>返回的信息，当请求成功时为Success</td>
        </tr>
        <tr>
            <td>code</td>
            <td>int</td>
            <td>返回码，详情请参阅<a href="<?= Url::toRoute(['index/code']);?>">错误码说明</a></td>
        </tr>
        <tr>
            <td>status</td>
            <td>int</td>
            <td>HTTP Status Code</td>
        </tr>
        <tr>
            <td>type</td>
            <td>string</td>
            <td>出错时的异常信息类型</td>
        </tr>
        <tr>
            <td>data</td>
            <td>array</td>
            <td>数据</td>
        </tr>
        </tbody>
    </table>
    <div class="page-header">
        <h5>data字段详细返回参数</h5>
    </div>
    <table class="table table-bordered" >
        <thead>
        <tr><th>返回字段</th><th>类型</th><th>说明</th></tr>
        </thead>
        <tbody>
        <?php if (!empty($notes['res'])){foreach ($notes['res'] as $k2){?>
            <tr>
                <td><?= $k2[1]?></td>
                <td><?= $k2[0]?></td>
                <td><?= $k2[2]?></td>
            </tr>
        <?php }}?>
        </tbody>
    </table>
    <div class="page-header">
        <h4><span class="glyphicon glyphicon-send" aria-hidden="true"></span> 请求模拟</h4>
    </div>
    <table class="table table-bordered" >
        <thead>
        <tr>
            <th>字段</th>
            <th>名称</th>
            <th>类型</th
            ><th>值</th>
        </tr>
        </thead>
        <tbody>
        <?php if($token != 0){?>
            <tr>
                <td>token</td>
                <td>访问令牌</td>
                <td>string</td>
                <td>
                    <textarea class="form-control" rows="6" name="token"></textarea>
                </td>
            </tr>
        <?php }?>
        <?php foreach ($notes['param'] as $v){?>
            <tr>
                <td><?= $v[1];?></td>
                <td><?= $v[2];?></td>
                <td><?= $v[0];?></td>
                <td class="td">
                    <input type="text" class="form-control" name="<?= $v[1];?>" value="<?= $v[4] ?? null;?>">
                </td>
            </tr>
        <?php }?>
        </tbody>
    </table>
    <div class="row" style="margin-bottom: 10px;">
        <div class="col-md-10" style="line-height: 2.4em;word-break: break-all;">
            <strong>接口地址：</strong>
            <span style="color: #953b39;"><?= $host_api . '/' . $route;?><span>
        </div>
        <div class="col-md-2">
            <button type="button" class="btn btn-success" id="submit">提交请求</button>
        </div>
    </div>
    <div class="alert alert-info" role="alert" id="json_output"></div>
    <div class="alert alert-success" role="alert">
        <strong>温馨提示：</strong> 此接口服务列表根据后台代码自动生成，如有疑问，请咨询PHP架构师 <?= $author;?>，邮箱：<a href="mailto:<?= $email;?>"><?= $email;?></a>
    </div>
</div>
<script>
    <?php $this->beginBlock('my_js');?>

    function getData() {
        var _data={};

        $(".td input").each(function(index,e) {
            if ($.trim(e.value)){
                _data[e.name] = e.value;
            }
        });

        return _data;
    }

    $(function(){
        $("#json_output").hide();
        $("#submit").on("click",function(){
            //var _header = getHeaderData();
            var _data = getData();
            //var url = $("textarea[name=request_url]").val();
            let url = '<?= $host_api . '/' . $route;?>';
            //console.log(url);
            var method = '<?= $notes['method'];?>';
            $.ajax({
                url: url,
                data: method=='POST' ? JSON.stringify(_data) : {},
                dataType: 'json',
                type: method,
                //headers: _header,
                contentType: 'application/json',
                beforeSend: function(request) {
                    <?php if($token != 0){?>
                    //request.setRequestHeader("token", $("textarea[name=token]").val());
                    request.setRequestHeader("Authorization", 'Bearer ' + $("textarea[name=token]").val());
                    <?php }?>
                },
                success:function(res,status,xhr){
                    //console.log(xhr);
                    var statu = xhr.status + ' ' + xhr.statusText;
                    var header = xhr.getAllResponseHeaders();
                    var json_text = JSON.stringify(res, null, 4);    // 缩进4个空格
                    $("#json_output").html('<code style="white-space: pre-wrap;word-wrap: break-word;color: #31708f;background-color: #d9edf7;">' + statu + '<br/>' + header + '<br/>' + json_text + '</code>');
                    $("#json_output").show();
                },
                error:function(error){
                    console.log(error);
                    var statu = error.status + ' ' + error.statusText;
                    var header = error.getAllResponseHeaders();
                    var json_text = JSON.stringify(error.responseJSON, null, 4);    // 缩进4个空格
                    $("#json_output").html('<code style="white-space: pre-wrap;word-wrap: break-word;color: #31708f;background-color: #d9edf7;">' + statu + '<br/>' + header + '<br/>' + json_text + '</code>');
                    $("#json_output").show();
                }
            })
        })
    });

    <?php $this->endBlock()?>
</script>

<?php $this->registerJs($this->blocks['my_js'],View::POS_END);?>

src/views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

$logo_src = $this->params['logo_src'] ?? '';
$icp_num = $this->params['icp_num'] ?? '';
$icp_website = $this->params['icp_website'] ?? '';
$company_start_year = $this->params['company_start_year'] ?? '';
$copyright_website = $this->params['copyright_website'] ?? '';
$is_show_fae = $this->params['is_show_fae'] ?? '';
$fae_name = $this->params['fae_name'] ?? '';
$fae_website = $this->params['fae_website'] ?? '';

use zhuzixian520\api_doc\ApiDocAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

$brandLabel = $logo_src ? '<img style="float: left;margin: -6px 8px 0 0;" src="' . $logo_src . '" height="32" width="32">' : '';

ApiDocAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <meta name="description" content="<?= Yii::$app->name;?>"/>
    <meta name="keywords" content="<?= Yii::$app->name;?>"/>
    <meta name="author" content="<?= Yii::$app->name;?>"/>
    <meta name="copyright" content="<?= Yii::$app->name;?>"/>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        //'brandLabel' => Yii::$app->name,
        //'brandImage' => '/img/logo_64_64.png',
        'brandLabel' => $brandLabel . '<span>' . Yii::$app->name . '</span>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Gii', 'url' => ['/gii']],
        ['label' => 'Debug', 'url' => ['/debug']],
    ];
    /*if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
        $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->username . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }*/
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <!--
        <p class="pull-left">&copy; <?//= Html::encode(Yii::$app->name) ?> <?//= date('Y') ?></p>

        <p class="pull-right"><?//= Yii::powered() ?></p>
        -->

        <p class="pull-left">
            Copyright &copy; <?php if ($company_start_year) {?><?= $company_start_year;?> - <?php }?><?= date('Y') ?>
            <?php if ($copyright_website) {?>
            <a href="<?= $copyright_website;?>" target="_blank" rel="nofollow">
            <?php }?>
                <?= Yii::$app->name;?>
            <?php if ($copyright_website) {?>
            </a>
            <?php }?>
             版权所有;
            <?php if ($icp_num) {?>
             <a href="<?= $icp_website;?>" target="_blank" rel="nofollow"><?= $icp_num;?></a>;
            <?php }?>
        </p>
        <p class="pull-right"><?php if ($is_show_fae) {?>技术支持：<a href="<?= $fae_website;?>" title="<?= $fae_name;?>" target="_blank" rel="nofollow"><?= $fae_name;?></a><?php }?> 基于Yii <?= Yii::getVersion();?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>